%% calculate_pooled_conditions_R2.m
% Compute pooled-across-conditions reconstruction R2 from condition-specific
% DLAG bestmodel*.mat files.
%
% Run this script after data_reconstruction.m.
%
% This script does not reconstruct data again.
% It loads each condition-specific bestmodel*.mat, reads seqEst.y and the
% 15 reconstruction fields generated by data_reconstruction.m, then computes
% pooled-across-conditions R2 by concatenating data across conditions in the
% R2 calculation.
%
% Important:
%   The pooled R2 is recomputed from y and yRecon fields.
%   It is NOT computed by averaging condition-wise R2 values.
%
% Output:
%   pooled_conditions_reconstruction_R2.mat
%
% Saved in the current script folder.
%
% Variables saved:
%   recon_R2_pooled_conditions
%   recon_R2
%   data_content
%   condition_list
%   runIdx
%   r2_specs

clc;
clear;

%% ------------------------------------------------------------------------
% User parameters
% -------------------------------------------------------------------------

data_content = 'raw_count';
% options usually include:
% raw_count, raw_fr, z_within_trial, z_within_condition,
% z_across_conditions, demean_count_within_trial, demean_fr_within_trial,
% demean_pooledsd_within_condition

data_condition = [1:16];
% Must be non-empty. This script pools condition-specific models.

runIdx = 1;

output_file_name = sprintf('%s_sum_all_conditions_reconstruction_R2.mat',data_content);

%% ------------------------------------------------------------------------
% Setup
% -------------------------------------------------------------------------

if isempty(data_condition)
    error('data_condition must be non-empty for pooled condition R2.');
end

condition_list = data_condition(:)';
numConditions = numel(condition_list);

scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir)
    scriptDir = pwd;
end

outFile = fullfile(scriptDir, output_file_name);

r2_specs = getReconstructionR2SpecsLocal();

fprintf('\n============================================================\n');
fprintf('Calculating pooled-across-conditions reconstruction R2\n');
fprintf('data_content: %s\n', data_content);
fprintf('runIdx: %d\n', runIdx);
fprintf('Number of conditions: %d\n', numConditions);
fprintf('Output file: %s\n', outFile);

%% ------------------------------------------------------------------------
% Locate and validate all condition-specific bestmodel files
% -------------------------------------------------------------------------

bestFiles = cell(1, numConditions);
yDims_ref = [];
yDim_ref = [];

for cond_i = 1:numConditions

    this_condition = condition_list(cond_i);
    baseDir = ['./FA_Dlag_', data_content, '_condition', num2str(this_condition)];
    tempfname = sprintf('%s/mat_results/run%03d', baseDir, runIdx);

    bestFiles{cond_i} = findOneFileLocal(tempfname, 'bestmodel*', true);

    fprintf('Condition %d best model: %s\n', ...
        this_condition, bestFiles{cond_i});

    S = load(bestFiles{cond_i}, 'bestModel', 'res', 'seqEst');

    requiredVars = {'bestModel', 'res', 'seqEst'};
    for v = 1:numel(requiredVars)
        if ~isfield(S, requiredVars{v})
            error('File %s is missing variable %s.', ...
                bestFiles{cond_i}, requiredVars{v});
        end
    end

    if ~isfield(S.res, 'estParams')
        error('File %s is missing res.estParams.', bestFiles{cond_i});
    end

    params = normalizeParamDimsLocal(S.res.estParams, S.bestModel);
    yDims = params.yDims;
    yDim = sum(yDims);

    if isempty(yDims_ref)
        yDims_ref = yDims;
        yDim_ref = yDim;
    else
        if ~isequal(yDims_ref, yDims)
            error('Condition %d has yDims different from the first condition.', ...
                this_condition);
        end
    end

    checkSeqEstFieldsLocal(S.seqEst, r2_specs, yDim);
end

numGroups = numel(yDims_ref);

%% ------------------------------------------------------------------------
% First pass: compute pooled per-neuron mean for each reconstruction field
%
% The mean is computed using all condition-specific data concatenated
% conceptually across time/trials. It is field-specific only because valid
% samples are defined by finite(Ytrue) & finite(Ypred).
% -------------------------------------------------------------------------

fprintf('\nFirst pass: computing pooled means...\n');

numSpecs = size(r2_specs, 1);
sumY = cell(numSpecs, 1);
countY = cell(numSpecs, 1);

for s = 1:numSpecs
    sumY{s} = zeros(yDim_ref, 1);
    countY{s} = zeros(yDim_ref, 1);
end

for cond_i = 1:numConditions

    this_condition = condition_list(cond_i);
    fprintf('  Reading condition %d for means...\n', this_condition);

    S = load(bestFiles{cond_i}, 'seqEst');
    seqEst = S.seqEst;

    Ytrue = [seqEst.y];

    if size(Ytrue, 1) ~= yDim_ref
        error('Condition %d Ytrue has %d rows, expected %d.', ...
            this_condition, size(Ytrue, 1), yDim_ref);
    end

    for s = 1:numSpecs

        fieldName = r2_specs{s, 2};
        Ypred = [seqEst.(fieldName)];

        if ~isequal(size(Ytrue), size(Ypred))
            error('Condition %d field %s has size mismatch with y.', ...
                this_condition, fieldName);
        end

        valid = isfinite(Ytrue) & isfinite(Ypred);

        Ytmp = Ytrue;
        Ytmp(~valid) = 0;

        sumY{s} = sumY{s} + sum(Ytmp, 2);
        countY{s} = countY{s} + sum(valid, 2);
    end
end

muY = cell(numSpecs, 1);

for s = 1:numSpecs
    mu = sumY{s} ./ countY{s};
    mu(countY{s} == 0) = NaN;
    muY{s} = mu;
end

%% ------------------------------------------------------------------------
% Second pass: accumulate RSS and TSS for each reconstruction field
% -------------------------------------------------------------------------

fprintf('\nSecond pass: accumulating RSS and TSS...\n');

RSS = cell(numSpecs, 1);
TSS = cell(numSpecs, 1);

for s = 1:numSpecs
    RSS{s} = zeros(yDim_ref, 1);
    TSS{s} = zeros(yDim_ref, 1);
end

for cond_i = 1:numConditions

    this_condition = condition_list(cond_i);
    fprintf('  Reading condition %d for RSS/TSS...\n', this_condition);

    S = load(bestFiles{cond_i}, 'seqEst');
    seqEst = S.seqEst;

    Ytrue = [seqEst.y];

    for s = 1:numSpecs

        fieldName = r2_specs{s, 2};
        Ypred = [seqEst.(fieldName)];

        valid = isfinite(Ytrue) & isfinite(Ypred);

        D = Ytrue - repmat(muY{s}, 1, size(Ytrue, 2));
        E = Ytrue - Ypred;

        D(~valid) = 0;
        E(~valid) = 0;

        RSS{s} = RSS{s} + sum(E.^2, 2);
        TSS{s} = TSS{s} + sum(D.^2, 2);
    end
end

%% ------------------------------------------------------------------------
% Build recon_R2_pooled_conditions
% -------------------------------------------------------------------------

fprintf('\nBuilding pooled R2 structure...\n');

recon_R2_pooled_conditions = struct();

for s = 1:numSpecs

    r2Name = r2_specs{s, 1};

    rss = RSS{s};
    tss = TSS{s};

    recon_R2_pooled_conditions.(r2Name).global_all = ...
        computeGlobalFromSumsLocal(rss, tss);

    recon_R2_pooled_conditions.(r2Name).global_by_group = nan(1, numGroups);
    recon_R2_pooled_conditions.(r2Name).neuron_by_group = cell(1, numGroups);

    neuronR2 = computeNeuronFromSumsLocal(rss, tss);

    for groupIdx = 1:numGroups
        rows = getGroupRowsLocal(yDims_ref, groupIdx);

        recon_R2_pooled_conditions.(r2Name).global_by_group(groupIdx) = ...
            computeGlobalFromSumsLocal(rss(rows), tss(rows));

        recon_R2_pooled_conditions.(r2Name).neuron_by_group{groupIdx} = ...
            neuronR2(rows);
    end
end

% Also save as recon_R2, so plotting code can reuse the same variable name.
recon_R2 = recon_R2_pooled_conditions;

%% ------------------------------------------------------------------------
% Save
% -------------------------------------------------------------------------

fprintf('Saving pooled R2 to: %s\n', outFile);

save(outFile, ...
    'recon_R2', ...
    '-v7.3');

fprintf('Done.\n');

%% ========================================================================
% Local functions
% ========================================================================

function r2_specs = getReconstructionR2SpecsLocal()
% The 15 reconstruction fields generated by the current data_reconstruction.m

r2_specs = {
    'use_across', ...
        'yRecon_use_across';

    'use_within', ...
        'yRecon_use_within';

    'use_all', ...
        'yRecon_use_all';

    'across_excl_within', ...
        'yRecon_across_excl_within';

    'within_excl_across', ...
        'yRecon_within_excl_across';

    'use_across_with_R', ...
        'yRecon_use_across_with_R';

    'use_within_with_R', ...
        'yRecon_use_within_with_R';

    'use_all_with_R', ...
        'yRecon_use_all_with_R';

    'across_excl_within_with_R', ...
        'yRecon_across_excl_within_with_R';

    'within_excl_across_with_R', ...
        'yRecon_within_excl_across_with_R';

    'use_across_keep_resid', ...
        'yRecon_use_across_keep_resid';

    'use_within_keep_resid', ...
        'yRecon_use_within_keep_resid';

    'use_all_keep_resid', ...
        'yRecon_use_all_keep_resid';

    'across_excl_within_keep_resid', ...
        'yRecon_across_excl_within_keep_resid';

    'within_excl_across_keep_resid', ...
        'yRecon_within_excl_across_keep_resid'
};
end

function checkSeqEstFieldsLocal(seqEst, r2_specs, yDim)
% Check that seqEst contains y and all reconstruction fields.

if ~isfield(seqEst, 'y')
    error('seqEst is missing field y.');
end

if isempty(seqEst)
    error('seqEst is empty.');
end

for n = 1:numel(seqEst)
    if isempty(seqEst(n).y)
        error('seqEst(%d).y is empty.', n);
    end

    if size(seqEst(n).y, 1) ~= yDim
        error('seqEst(%d).y has %d rows, expected %d.', ...
            n, size(seqEst(n).y, 1), yDim);
    end
end

for s = 1:size(r2_specs, 1)

    fieldName = r2_specs{s, 2};

    if ~isfield(seqEst, fieldName)
        error('seqEst is missing reconstruction field %s.', fieldName);
    end

    for n = 1:numel(seqEst)
        if isempty(seqEst(n).(fieldName))
            error('seqEst(%d).%s is empty.', n, fieldName);
        end

        if ~isequal(size(seqEst(n).(fieldName)), size(seqEst(n).y))
            error('seqEst(%d).%s size does not match seqEst(%d).y.', ...
                n, fieldName, n);
        end
    end
end
end

function R2 = computeGlobalFromSumsLocal(rss, tss)
% Compute global R2 from accumulated per-neuron RSS and TSS.

rssTotal = sum(rss(:));
tssTotal = sum(tss(:));

if tssTotal > 0 && isfinite(tssTotal)
    R2 = 1 - rssTotal / tssTotal;
else
    R2 = NaN;
end
end

function R2 = computeNeuronFromSumsLocal(rss, tss)
% Compute neuron-wise R2 from accumulated per-neuron RSS and TSS.

R2 = nan(numel(rss), 1);

valid = tss > 0 & isfinite(tss) & isfinite(rss);

R2(valid) = 1 - rss(valid) ./ tss(valid);
end

function params = normalizeParamDimsLocal(params, bestModel)
% Normalize params.yDims, params.xDim_across, and params.xDim_within.
% Only yDims is essential here, but keeping the same helper as other scripts
% makes this robust to saved parameter format.

if ~isfield(params, 'yDims')
    error('params must contain yDims.');
end

params.yDims = reshape(params.yDims, 1, []);
numGroups = numel(params.yDims);

if ~isfield(params, 'xDim_across') || isempty(params.xDim_across)
    if ~isempty(bestModel) && isfield(bestModel, 'xDim_across')
        params.xDim_across = bestModel.xDim_across;
    else
        params.xDim_across = 0;
    end
end

if ~isfield(params, 'xDim_within') || isempty(params.xDim_within)
    if ~isempty(bestModel) && isfield(bestModel, 'xDim_within')
        params.xDim_within = bestModel.xDim_within;
    else
        params.xDim_within = zeros(1, numGroups);
    end
end

params.xDim_within = reshape(params.xDim_within, 1, []);

if isscalar(params.xDim_within) && numGroups > 1
    params.xDim_within = repmat(params.xDim_within, 1, numGroups);
end
end

function rows = getGroupRowsLocal(yDims, groupIdx)
% Row indices for one observed group.

startIdx = sum(yDims(1:groupIdx-1)) + 1;
rows = startIdx:(startIdx + yDims(groupIdx) - 1);
end

function fname = findOneFileLocal(parentDir, pattern, mustExist)
% Return the newest file matching pattern in parentDir.

if ~exist(parentDir, 'dir')
    error('Directory not found: %s', parentDir);
end

files = dir(fullfile(parentDir, pattern));

if isempty(files)
    if mustExist
        error('No %s file found in %s.', pattern, parentDir);
    else
        fname = '';
        return;
    end
end

[~, idx] = sort([files.datenum], 'descend');
files = files(idx);

fname = fullfile(parentDir, files(1).name);
end