%% =========================================================================
% size_effect_comparation.m
%
% Purpose:
% Compare size effect metrics across different analysis fields.
%
% This script is a downstream analysis of plot_size_effect.m.
% It does not recompute size effect from seqEst. Instead, it loads saved
% size_effect_result files generated by plot_size_effect.m.
%
% For each metric:
%   - make one summary figure
%   - each panel is one baseline_field x comparation_field comparison
%   - x-axis: baseline field size effect metric
%   - y-axis: compared field size effect metric
%   - all groups are plotted in the same panel with different colors
%
% Expected input mat names from plot_size_effect.m:
%   <data_content>_<model_mode>_size_effect_<field>.mat
%
% Example:
%   raw_count_all_condition_model_size_effect_y.mat
%   raw_count_all_condition_model_size_effect_yRecon_use_all.mat
%   raw_count_condition_specific_models_size_effect_y.mat
%
% Output figure name:
%   <data_content>_base_<all_base_fields>_compared_<all_compared_fields>_<metric>_<model_mode>
%
% Path convention:
%   model_mode = 'all_condition_model'
%       read/save in ./FA_Dlag_<data_content>/mat_results/runXXX/
%
%   model_mode = 'condition_specific_models'
%       read/save in this script's folder
%
% Plot style:
%   - Group colors follow plot_reconstruction_R2.m / RF_analysis.m style.
%   - Each panel has y = x, x = 0, and y = 0 dashed reference lines.
% =========================================================================

clc;
clear;

%% ----------------------- User parameters -----------------------

data_content = 'demean_count_within_trial';
% options:
% raw_count, raw_fr, z_within_trial, z_within_condition,
% z_across_conditions, demean_count_within_trial,
% demean_fr_within_trial, demean_pooledsd_within_condition


% Options:
%   'all_condition_model'
%   'condition_specific_models'
model_mode = 'all_condition_model';

runIdx = 1;

% Fields to analyze from seqEst.
%
% Example:
% analysis_fields = {'y'};
% analysis_fields = {'y', 'yRecon_use_all', 'yRecon_use_across'};
%
% Original data:
%   y
%
% Base noiseless reconstruction fields after data_reconstruction.m:
%   yRecon_use_across
%   yRecon_use_within
%   yRecon_use_all
%   yRecon_across_excl_within
%   yRecon_within_excl_across
%
% Reconstruction fields with R noise, if generated:
%   yRecon_use_across_with_R
%   yRecon_use_within_with_R
%   yRecon_use_all_with_R
%   yRecon_across_excl_within_with_R
%   yRecon_within_excl_across_with_R
%
% Reconstruction fields keeping residual, if generated:
%   yRecon_use_across_keep_resid
%   yRecon_use_within_keep_resid
%   yRecon_use_all_keep_resid
%   yRecon_across_excl_within_keep_resid
%   yRecon_within_excl_across_keep_resid

% Baseline fields used on x-axis.
baseline_fields = {'yRecon_use_all'};

% Compared fields used on y-axis.
comparation_fields = { ...
    'yRecon_use_across',...
    'yRecon_across_excl_within',...
    'yRecon_use_within',...
    'yRecon_within_excl_across',...
    };

% Metrics to compare.
% Available from plot_size_effect.m:
%   classic_SI
%   delta_SL
%   S_norm_diff
metrics = {'delta_SL'};

% Optional manual group names.
% If empty, use size_effect_result.group_names if available.
group_names = {};

% Save options.
save_fig = true;
save_png = true;
save_matlab_fig = true;
close_after_save = true;

% Figure options.
figure_visible = 'on';
png_dpi = 300;

% Scatter style, matched to plot_reconstruction_R2.m style.
marker_size = 30;
use_marker_alpha = true;
marker_alpha = 0.65;

% Same colors as plot_reconstruction_R2.m / RF_analysis.m.
% Row 1 is probe 0 / group 1, row 2 is probe 1 / group 2.
probe_colors = [ ...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980];

% Reference line style.
reference_line_width = 1.0;
zero_line_width = 1.0;
reference_line_style = 'k--';

% Panel layout.
max_panel_cols = 4;
fig_base_width_per_col = 470;
fig_base_height_per_row = 420;
fig_min_width = 900;
fig_min_height = 600;

%% ----------------------- Main setup -----------------------

scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir)
    scriptDir = pwd;
end

baseline_fields = normalize_field_list_local(baseline_fields, 'baseline_fields');
comparation_fields = normalize_field_list_local(comparation_fields, 'comparation_fields');
metrics = normalize_field_list_local(metrics, 'metrics');

safe_data_content = sanitize_filename_local(data_content);

io_dir = resolve_size_effect_io_dir_local(data_content, model_mode, runIdx, scriptDir);

if ~exist(io_dir, 'dir')
    error('Input/output folder does not exist:\n  %s', io_dir);
end

fprintf('Data content: %s\n', data_content);
fprintf('Model mode: %s\n', model_mode);
fprintf('Input/output folder:\n  %s\n', io_dir);

fprintf('\nBaseline fields:\n');
disp(baseline_fields(:));

fprintf('Compared fields:\n');
disp(comparation_fields(:));

fprintf('Metrics:\n');
disp(metrics(:));

%% ----------------------- Load all required size effect results -----------------------

all_fields = unique([baseline_fields, comparation_fields], 'stable');
result_map = struct();

for f = 1:numel(all_fields)
    field_name = all_fields{f};
    key = field_to_key_local(field_name);

    result_file = build_size_effect_mat_file_local( ...
        io_dir, safe_data_content, model_mode, field_name);

    fprintf('\nLoading size effect result for field %s:\n  %s\n', ...
        field_name, result_file);

    result_map.(key) = load_size_effect_result_local(result_file, field_name);
end

%% ----------------------- Validate shared metadata across all fields -----------------------

reference_field = all_fields{1};
reference_result = result_map.(field_to_key_local(reference_field));

nUnits = reference_result.nUnits;
groupd = reference_result.groupd(:)';
nGroups = numel(groupd);

group_names = resolve_group_names_local(group_names, reference_result, nGroups);
group_colors = resolve_group_colors_local(probe_colors, nGroups);

for f = 2:numel(all_fields)
    this_field = all_fields{f};
    this_result = result_map.(field_to_key_local(this_field));

    validate_compatible_results_local( ...
        reference_result, this_result, ...
        reference_field, this_field, ...
        data_content, model_mode);
end

group_row_ranges = build_group_row_ranges_local(groupd);

%% ----------------------- Build abbreviated output filename prefix -----------------------

base_fields_tag = join_short_field_names_for_filename_local(baseline_fields);
compared_fields_tag = join_short_field_names_for_filename_local(comparation_fields);
mode_file_tag = model_mode_to_file_tag_local(model_mode);

output_prefix = sprintf('%s_b-%s_c-%s', ...
    safe_data_content, base_fields_tag, compared_fields_tag);

%% ----------------------- Plot one figure per metric -----------------------

nBase = numel(baseline_fields);
nComp = numel(comparation_fields);
nPanels = nBase * nComp;

[nRows, nCols] = choose_panel_layout_local(nPanels, max_panel_cols);

figWidth = max(fig_min_width, fig_base_width_per_col * nCols);
figHeight = max(fig_min_height, fig_base_height_per_row * nRows);

for m = 1:numel(metrics)

    metric_name = metrics{m};
    safe_metric = sanitize_filename_local(metric_name);

    fprintf('\n============================================================\n');
    fprintf('Plotting metric %d/%d: %s\n', m, numel(metrics), metric_name);
    fprintf('============================================================\n');

    hfig = figure( ...
        'Color', 'w', ...
        'Visible', figure_visible, ...
        'Name', sprintf('Size effect comparation: %s', metric_name), ...
        'Position', [100 100 figWidth figHeight]);

    tl = tiledlayout(hfig, nRows, nCols, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    panel_idx = 0;
    legend_handles = gobjects(nGroups, 1);

    for b = 1:nBase
        baseline_field = baseline_fields{b};
        baseline_result = result_map.(field_to_key_local(baseline_field));

        for c = 1:nComp
            comparation_field = comparation_fields{c};
            comparation_result = result_map.(field_to_key_local(comparation_field));

            panel_idx = panel_idx + 1;
            ax = nexttile(tl, panel_idx);
            hold(ax, 'on');

            if ~isfield(baseline_result, metric_name)
                error('Metric %s not found in baseline field result %s.', ...
                    metric_name, baseline_field);
            end

            if ~isfield(comparation_result, metric_name)
                error('Metric %s not found in compared field result %s.', ...
                    metric_name, comparation_field);
            end

            x_all = baseline_result.(metric_name);
            y_all = comparation_result.(metric_name);

            x_all = x_all(:);
            y_all = y_all(:);

            if numel(x_all) ~= nUnits || numel(y_all) ~= nUnits
                error(['Metric vector length mismatch for %s vs %s, metric %s. ', ...
                    'Expected %d units, got %d and %d.'], ...
                    baseline_field, comparation_field, metric_name, ...
                    nUnits, numel(x_all), numel(y_all));
            end

            valid_all = isfinite(x_all) & isfinite(y_all);
            all_x = x_all(valid_all);
            all_y = y_all(valid_all);

            [axis_min, axis_max] = compute_shared_axis_limits_local(all_x, all_y);

            % Force every panel to contain zero, so x = 0 and y = 0
            % reference lines are always visible.
            axis_min = min(axis_min, 0);
            axis_max = max(axis_max, 0);

            if axis_min == axis_max
                axis_min = axis_min - 1;
                axis_max = axis_max + 1;
            end

            % Diagonal reference line y = x.
            plot(ax, [axis_min axis_max], [axis_min axis_max], ...
                reference_line_style, ...
                'LineWidth', reference_line_width, ...
                'HandleVisibility', 'off');

            % Zero reference lines x = 0 and y = 0.
            plot(ax, [0 0], [axis_min axis_max], ...
                reference_line_style, ...
                'LineWidth', zero_line_width, ...
                'HandleVisibility', 'off');

            plot(ax, [axis_min axis_max], [0 0], ...
                reference_line_style, ...
                'LineWidth', zero_line_width, ...
                'HandleVisibility', 'off');

            for g = 1:nGroups
                rows = group_row_ranges{g};

                x = x_all(rows);
                y = y_all(rows);

                valid = isfinite(x) & isfinite(y);
                x = x(valid);
                y = y(valid);

                if isempty(x)
                    continue;
                end

                thisColor = group_colors(g, :);

                if use_marker_alpha
                    h = scatter(ax, x, y, marker_size, ...
                        'filled', ...
                        'MarkerFaceColor', thisColor, ...
                        'MarkerEdgeColor', thisColor, ...
                        'MarkerFaceAlpha', marker_alpha, ...
                        'MarkerEdgeAlpha', marker_alpha, ...
                        'DisplayName', group_names{g});
                else
                    h = scatter(ax, x, y, marker_size, ...
                        'filled', ...
                        'MarkerFaceColor', thisColor, ...
                        'MarkerEdgeColor', thisColor, ...
                        'DisplayName', group_names{g});
                end

                if panel_idx == 1
                    legend_handles(g) = h;
                end
            end

            axis(ax, 'square');
            xlim(ax, [axis_min axis_max]);
            ylim(ax, [axis_min axis_max]);

            xlabel(ax, sprintf('%s %s', baseline_field, metric_label_local(metric_name)), ...
                'Interpreter', 'none');

            ylabel(ax, sprintf('%s %s', comparation_field, metric_label_local(metric_name)), ...
                'Interpreter', 'none');

            title(ax, sprintf('base: %s\ncompared: %s', ...
                baseline_field, comparation_field), ...
                'Interpreter', 'none');

            clean_axis_local(ax);
        end
    end

    sgtitle(tl, sprintf('%s | %s | %s | neuron-wise size effect comparation', ...
        data_content, model_mode, metric_name), ...
        'Interpreter', 'none');

    valid_legend_handles = legend_handles(isgraphics(legend_handles));
    if ~isempty(valid_legend_handles)
        legend_names = group_names(isgraphics(legend_handles));
        lgd = legend(valid_legend_handles, legend_names, ...
            'Interpreter', 'none', ...
            'Location', 'eastoutside', ...
            'Box', 'off');
        lgd.Layout.Tile = 'east';
    end

metric_file_tag = metric_to_file_tag_local(metric_name);

output_base_name = sprintf('%s_%s_%s', ...
    output_prefix, metric_file_tag, mode_file_tag);

    if save_fig
        save_current_figure_local(hfig, io_dir, output_base_name, ...
            save_png, save_matlab_fig, png_dpi);
    end

    if close_after_save
        close(hfig);
    end
end

fprintf('\nDone.\n');

%% =========================================================================
% Local functions
% =========================================================================

function fields = normalize_field_list_local(fields, var_name)
    if ischar(fields)
        fields = {fields};

    elseif isstring(fields)
        fields = cellstr(fields(:))';

    elseif iscell(fields)
        fields = reshape(fields, 1, []);

        for i = 1:numel(fields)
            if isstring(fields{i})
                fields{i} = char(fields{i});
            end

            if ~ischar(fields{i})
                error('%s{%d} must be a char or string.', var_name, i);
            end
        end

    else
        error('%s must be a char, string, string array, or cell array.', var_name);
    end

    if isempty(fields)
        error('%s is empty.', var_name);
    end

    empty_mask = cellfun(@isempty, fields);
    if any(empty_mask)
        error('%s contains empty entries.', var_name);
    end

    if numel(unique(fields, 'stable')) ~= numel(fields)
        warning('%s contains duplicate entries. Duplicates will be removed.', var_name);
        fields = unique(fields, 'stable');
        fields = reshape(fields, 1, []);
    end
end

function io_dir = resolve_size_effect_io_dir_local(data_content, model_mode, runIdx, scriptDir)
    switch model_mode
        case 'all_condition_model'
            baseDir = ['./FA_Dlag_', data_content];
            io_dir = fullfile(baseDir, 'mat_results', sprintf('run%03d', runIdx));

        case 'condition_specific_models'
            io_dir = scriptDir;

        otherwise
            error(['Unknown model_mode: %s. Expected all_condition_model ', ...
                'or condition_specific_models.'], model_mode);
    end
end

function result_file = build_size_effect_mat_file_local( ...
    io_dir, safe_data_content, model_mode, field_name)

    safe_field = sanitize_filename_local(field_name);

    result_file = fullfile(io_dir, sprintf('%s_%s_size_effect_%s.mat', ...
        safe_data_content, model_mode, safe_field));

    if ~isfile(result_file)
        error('Size effect result file not found:\n  %s', result_file);
    end
end

function result = load_size_effect_result_local(result_file, expected_field)
    S = load(result_file);

    if ~isfield(S, 'size_effect_result')
        error('File does not contain size_effect_result:\n  %s', result_file);
    end

    result = S.size_effect_result;

    required_fields = { ...
        'data_content', ...
        'model_mode', ...
        'analysis_field', ...
        'nUnits', ...
        'groupd', ...
        'classic_SI', ...
        'delta_SL', ...
        'S_norm_diff'};

    for i = 1:numel(required_fields)
        if ~isfield(result, required_fields{i})
            error('size_effect_result in %s is missing field %s.', ...
                result_file, required_fields{i});
        end
    end

    if ~strcmp(result.analysis_field, expected_field)
        warning(['Loaded result file analysis_field is %s, but expected %s. ', ...
            'Continuing because file name matched expected field.'], ...
            result.analysis_field, expected_field);
    end
end

function validate_compatible_results_local( ...
    reference_result, this_result, reference_field, this_field, ...
    expected_data_content, expected_model_mode)

    if ~strcmp(this_result.data_content, expected_data_content)
        error('Field %s data_content is %s, expected %s.', ...
            this_field, this_result.data_content, expected_data_content);
    end

    if ~strcmp(this_result.model_mode, expected_model_mode)
        error('Field %s model_mode is %s, expected %s.', ...
            this_field, this_result.model_mode, expected_model_mode);
    end

    if ~strcmp(reference_result.data_content, this_result.data_content)
        error('data_content mismatch between %s and %s.', ...
            reference_field, this_field);
    end

    if ~strcmp(reference_result.model_mode, this_result.model_mode)
        error('model_mode mismatch between %s and %s.', ...
            reference_field, this_field);
    end

    if reference_result.nUnits ~= this_result.nUnits
        error('nUnits mismatch between %s and %s: %d vs %d.', ...
            reference_field, this_field, reference_result.nUnits, this_result.nUnits);
    end

    if ~isequal(reference_result.groupd(:)', this_result.groupd(:)')
        error('groupd mismatch between %s and %s.', ...
            reference_field, this_field);
    end

    optional_compare_fields = { ...
        'runIdx', ...
        'stim_tag', ...
        'small_size', ...
        'large_size', ...
        'n_small_trials', ...
        'n_large_trials'};

    for i = 1:numel(optional_compare_fields)
        fn = optional_compare_fields{i};

        if isfield(reference_result, fn) && isfield(this_result, fn)
            ref_val = reference_result.(fn);
            this_val = this_result.(fn);

            if ischar(ref_val) || isstring(ref_val)
                if ~strcmp(char(ref_val), char(this_val))
                    warning('%s differs between %s and %s.', ...
                        fn, reference_field, this_field);
                end
            elseif isnumeric(ref_val) || islogical(ref_val)
                if ~isequal(ref_val, this_val)
                    warning('%s differs between %s and %s.', ...
                        fn, reference_field, this_field);
                end
            end
        end
    end
end

function group_names = resolve_group_names_local(group_names, result, nGroups)
    if isempty(group_names)
        if isfield(result, 'group_names') && ~isempty(result.group_names)
            group_names = result.group_names;
        else
            group_names = cell(1, nGroups);
            for g = 1:nGroups
                group_names{g} = sprintf('Group %d neurons', g);
            end
        end
    end

    if isstring(group_names)
        group_names = cellstr(group_names);
    end

    group_names = reshape(group_names, 1, []);

    if ~iscell(group_names) || numel(group_names) ~= nGroups
        error('group_names must be empty or contain exactly %d entries.', nGroups);
    end

    for g = 1:nGroups
        if isstring(group_names{g})
            group_names{g} = char(group_names{g});
        end

        if ~ischar(group_names{g})
            error('group_names{%d} must be a char or string.', g);
        end
    end
end

function group_colors = resolve_group_colors_local(probe_colors, nGroups)
    if size(probe_colors, 1) < nGroups
        warning(['probe_colors has fewer rows than number of groups. ', ...
            'Extra groups will be plotted in black.']);
    end

    group_colors = zeros(nGroups, 3);

    for g = 1:nGroups
        if g <= size(probe_colors, 1)
            group_colors(g, :) = probe_colors(g, :);
        else
            group_colors(g, :) = [0, 0, 0];
        end
    end
end

function group_row_ranges = build_group_row_ranges_local(groupd)
    groupd = groupd(:)';
    nGroups = numel(groupd);
    group_row_ranges = cell(1, nGroups);

    row_start = 1;
    for g = 1:nGroups
        row_end = row_start + groupd(g) - 1;
        group_row_ranges{g} = row_start:row_end;
        row_start = row_end + 1;
    end
end

function [axis_min, axis_max] = compute_shared_axis_limits_local(x, y)
    vals = [x(:); y(:)];
    vals = vals(isfinite(vals));

    if isempty(vals)
        axis_min = -1;
        axis_max = 1;
        return;
    end

    axis_min = min(vals);
    axis_max = max(vals);

    if axis_min == axis_max
        pad = max(1e-6, abs(axis_min) * 0.05);
        axis_min = axis_min - pad;
        axis_max = axis_max + pad;
        return;
    end

    pad = 0.06 * (axis_max - axis_min);
    axis_min = axis_min - pad;
    axis_max = axis_max + pad;
end

function label = metric_label_local(metric_name)
    switch metric_name
        case 'classic_SI'
            label = 'classic SI';

        case 'delta_SL'
            label = 'delta S-L';

        case 'S_norm_diff'
            label = 'S norm diff';

        otherwise
            label = metric_name;
    end
end

function joined_name = join_field_names_for_filename_local(fields)
    safe_fields = cell(size(fields));

    for i = 1:numel(fields)
        safe_fields{i} = sanitize_filename_local(fields{i});
    end

    joined_name = strjoin(safe_fields, '_');
end

function key = field_to_key_local(field_name)
    key = sanitize_filename_local(field_name);

    if isempty(regexp(key(1), '[A-Za-z]', 'once'))
        key = ['field_', key];
    end

    key = matlab.lang.makeValidName(key);
end

function clean_axis_local(ax)
    grid(ax, 'off');
    box(ax, 'off');
    set(ax, ...
        'TickDir', 'out', ...
        'LineWidth', 1, ...
        'FontSize', 11);
end

function save_current_figure_local(hfig, fig_out_dir, base_name, save_png, save_matlab_fig, png_dpi)
    if ~exist(fig_out_dir, 'dir')
        mkdir(fig_out_dir);
    end

    if save_png
        png_file = fullfile(fig_out_dir, sprintf('%s.png', base_name));
        save_png_local(hfig, png_file, png_dpi);
        fprintf('\nSaved PNG figure:\n  %s\n', png_file);
    end

    if save_matlab_fig
        fig_file = fullfile(fig_out_dir, sprintf('%s.fig', base_name));
        savefig(hfig, fig_file);
        fprintf('Saved MATLAB figure:\n  %s\n', fig_file);
    end
end

function save_png_local(fig, pngFile, dpi)
    drawnow;

    try
        if exist('exportgraphics', 'file') == 2
            exportgraphics(fig, pngFile, ...
                'Resolution', dpi, ...
                'BackgroundColor', 'white');
        else
            set(fig, 'PaperPositionMode', 'auto');
            print(fig, pngFile, '-dpng', sprintf('-r%d', dpi));
        end
    catch
        warning('exportgraphics/print failed. Falling back to saveas.');
        saveas(fig, pngFile);
    end
end

function name = sanitize_filename_local(name)
    if isstring(name)
        name = char(name);
    end

    name = regexprep(name, '[^a-zA-Z0-9_\-]', '_');
    name = regexprep(name, '_+', '_');
    name = strtrim(name);

    if isempty(name)
        name = 'unnamed';
    end
end


function [nRows, nCols] = choose_panel_layout_local(nPanels, max_panel_cols)
    if nPanels < 1
        error('nPanels must be >= 1.');
    end

    if nargin < 2 || isempty(max_panel_cols)
        max_panel_cols = 4;
    end

    max_panel_cols = max(1, max_panel_cols);
    max_panel_cols = min(max_panel_cols, nPanels);

    best_score = inf;
    best_rows = 1;
    best_cols = 1;

    for c = 1:max_panel_cols
        r = ceil(nPanels / c);
        empty_panels = r * c - nPanels;

        % Prefer layouts close to square, but slightly wider than tall.
        aspect_penalty = abs(c / r - 1.35);

        % Strongly penalize empty panels.
        empty_penalty = empty_panels * 10;

        % Mildly penalize too many rows.
        row_penalty = r * 0.1;

        score = empty_penalty + aspect_penalty + row_penalty;

        if score < best_score
            best_score = score;
            best_rows = r;
            best_cols = c;
        end
    end

    nRows = best_rows;
    nCols = best_cols;
end

function data_tag = data_content_to_file_tag_local(data_content)
    switch data_content
        case 'raw_count'
            data_tag = 'rc';

        case 'raw_fr'
            data_tag = 'rfr';

        case 'z_within_trial'
            data_tag = 'zWT';

        case 'z_within_condition'
            data_tag = 'zWC';

        case 'z_across_conditions'
            data_tag = 'zAC';

        case 'demean_count_within_trial'
            data_tag = 'dcntWT';

        case 'demean_fr_within_trial'
            data_tag = 'dfrWT';

        case 'demean_pooledsd_within_condition'
            data_tag = 'dpsdWC';

        otherwise
            data_tag = sanitize_filename_local(data_content);
            data_tag = compress_generic_name_local(data_tag);
    end
end

function mode_tag = model_mode_to_file_tag_local(model_mode)
    switch model_mode
        case 'all_condition_model'
            mode_tag = 'all';

        case 'condition_specific_models'
            mode_tag = 'csm';

        otherwise
            mode_tag = sanitize_filename_local(model_mode);
            mode_tag = compress_generic_name_local(mode_tag);
    end
end

function metric_tag = metric_to_file_tag_local(metric_name)
    switch metric_name
        case 'classic_SI'
            metric_tag = 'SI';

        case 'delta_SL'
            metric_tag = 'dSL';

        case 'S_norm_diff'
            metric_tag = 'SnD';

        otherwise
            metric_tag = sanitize_filename_local(metric_name);
            metric_tag = compress_generic_name_local(metric_tag);
    end
end

function joined_name = join_short_field_names_for_filename_local(fields)
    short_fields = cell(size(fields));

    for i = 1:numel(fields)
        short_fields{i} = analysis_field_to_file_tag_local(fields{i});
    end

    joined_name = strjoin(short_fields, '-');
end

function field_tag = analysis_field_to_file_tag_local(field_name)
    switch field_name
        case 'y'
            field_tag = 'y';

        case 'yRecon_use_all'
            field_tag = 'yall';

        case 'yRecon_use_across'
            field_tag = 'yacr';

        case 'yRecon_use_within'
            field_tag = 'ywin';

        case 'yRecon_across_excl_within'
            field_tag = 'yacrXwin';

        case 'yRecon_within_excl_across'
            field_tag = 'ywinXacr';

        case 'yRecon_use_all_with_R'
            field_tag = 'yallR';

        case 'yRecon_use_across_with_R'
            field_tag = 'yacrR';

        case 'yRecon_use_within_with_R'
            field_tag = 'ywinR';

        case 'yRecon_across_excl_within_with_R'
            field_tag = 'yacrXwinR';

        case 'yRecon_within_excl_across_with_R'
            field_tag = 'ywinXacrR';

        case 'yRecon_use_all_keep_resid'
            field_tag = 'yallKR';

        case 'yRecon_use_across_keep_resid'
            field_tag = 'yacrKR';

        case 'yRecon_use_within_keep_resid'
            field_tag = 'ywinKR';

        case 'yRecon_across_excl_within_keep_resid'
            field_tag = 'yacrXwinKR';

        case 'yRecon_within_excl_across_keep_resid'
            field_tag = 'ywinXacrKR';

        otherwise
            field_tag = sanitize_filename_local(field_name);
            field_tag = strrep(field_tag, 'yRecon_', 'y');
            field_tag = strrep(field_tag, 'use_', '');
            field_tag = strrep(field_tag, 'across', 'acr');
            field_tag = strrep(field_tag, 'within', 'win');
            field_tag = strrep(field_tag, 'excl', 'X');
            field_tag = strrep(field_tag, 'condition', 'cond');
            field_tag = strrep(field_tag, 'resid', 'res');
            field_tag = compress_generic_name_local(field_tag);
    end
end

function short_name = compress_generic_name_local(name)
    short_name = name;

    replacements = { ...
        'demean', 'dm'; ...
        'count', 'cnt'; ...
        'within', 'win'; ...
        'trial', 'tr'; ...
        'condition', 'cond'; ...
        'conditions', 'conds'; ...
        'across', 'acr'; ...
        'pooled', 'pool'; ...
        'reconstruction', 'recon'; ...
        'specific', 'spec'; ...
        'model', 'mdl'; ...
        'models', 'mdls'};

    for i = 1:size(replacements, 1)
        short_name = strrep(short_name, replacements{i, 1}, replacements{i, 2});
    end

    short_name = regexprep(short_name, '_+', '_');
    short_name = regexprep(short_name, '^_|_$', '');
end