%% =========================================================================
% size_effect_comparation.m
%
% Purpose:
% Compare size effect metrics across different analysis fields.
%
% This script is a downstream analysis of plot_size_effect.m.
% It does not recompute size effect from seqEst. Instead, it loads saved
% size_effect_result files generated by plot_size_effect.m.
%
% For each metric:
%   - make one summary figure
%   - each panel is one baseline_field x comparation_field comparison
%   - x-axis: baseline field size effect metric
%   - y-axis: compared field size effect metric
%   - all groups are plotted in the same panel with different colors
%
% Expected input mat names from plot_size_effect.m:
%   <data_content>_<model_mode>_size_effect_<field><contrast_suffix>.mat
%
% Example:
%   raw_count_all_condition_model_size_effect_y.mat
%   raw_count_all_condition_model_size_effect_yRecon_use_all.mat
%   raw_count_condition_specific_models_size_effect_y.mat
%   raw_count_all_condition_model_size_effect_y_low_contrast.mat
%   raw_count_all_condition_model_size_effect_y_high_contrast.mat
%
% Output figure name uses abbreviated field/mode/metric tags:
%   <data_content>_b-<base_tags>_c-<compared_tags>_<metric_tag>_<mode_tag><contrast_suffix>
%
% Path convention:
%   model_mode = 'all_condition_model'
%       read/save in ./FA_Dlag_<data_content>/mat_results/runXXX/
%
%   model_mode = 'condition_specific_models'
%       read/save in this script's folder
%
% Plot style:
%   - Group colors follow plot_reconstruction_R2.m / RF_analysis.m style.
%   - Each panel has y = x, x = 0, and y = 0 dashed reference lines.
% =========================================================================

clc;
clear;

%% ----------------------- User parameters -----------------------

data_content = 'raw_count';
% options:
% raw_count, raw_fr, z_within_trial, z_within_condition,
% z_across_conditions, demean_count_within_trial,
% demean_fr_within_trial, demean_pooledsd_within_condition


% Options:
%   'all_condition_model'
%   'condition_specific_models'
model_mode = 'all_condition_model';

runIdx = 1;

% Optional contrast selection, matching plot_size_effect.m.
%   0: no contrast filter, old behavior.
%   1: low contrast only.
%   2: high contrast only.
%
% Important:
% This script does not recompute or refilter trials. It only loads the
% corresponding size_effect_result files generated by plot_size_effect.m.
% Therefore, pick_contrast must match the value used in plot_size_effect.m.
pick_contrast = 2;

% Fields to analyze from seqEst.
%
% Example:
% analysis_fields = {'y'};
% analysis_fields = {'y', 'yRecon_use_all', 'yRecon_use_across'};
%
% Original data:
%   y
%
% Base noiseless reconstruction fields after data_reconstruction.m:
%   d
%   yRecon_use_across
%   yRecon_use_within
%   yRecon_use_all
%   yRecon_use_across_no_d
%   yRecon_use_within_no_d
%   yRecon_use_all_no_d
%   yRecon_across_excl_within
%   yRecon_within_excl_across
%
% Reconstruction fields with R noise, if generated:
%   yRecon_use_across_with_R
%   yRecon_use_within_with_R
%   yRecon_use_all_with_R
%   yRecon_across_excl_within_with_R
%   yRecon_within_excl_across_with_R
%
% Reconstruction fields keeping residual, if generated:
%   yRecon_use_across_keep_resid
%   yRecon_use_within_keep_resid
%   yRecon_use_all_keep_resid
%   yRecon_across_excl_within_keep_resid
%   yRecon_within_excl_across_keep_resid

% Baseline fields used on x-axis.
baseline_fields = {'yRecon_use_all'};

% Compared fields used on y-axis.
comparation_fields = { ...
    'yRecon_use_across'...
    'yRecon_across_excl_within'...
    'yRecon_use_within'...
    'yRecon_within_excl_across'};

% Metrics to compare.
% Available from plot_size_effect.m:
%   classic_SI
%   delta_SL
%   S_norm_diff
metrics = {'S_norm_diff'};

% Optional manual group names.
% If empty, use size_effect_result.group_names if available.
group_names = {};

% Save options.
save_fig = true;
save_png = true;
save_matlab_fig = true;
close_after_save = false;

% Figure options.
figure_visible = 'on';
png_dpi = 300;

% Scatter style, matched to plot_reconstruction_R2.m style.
marker_size = 30;
use_marker_alpha = true;
marker_alpha = 0.65;

% Same colors as plot_reconstruction_R2.m / RF_analysis.m.
% Row 1 is probe 0 / group 1, row 2 is probe 1 / group 2.
probe_colors = [ ...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980];

% Reference line style.
reference_line_width = 1.0;
zero_line_width = 1.0;
reference_line_style = 'k--';

% Panel layout.
max_panel_cols = 4;
fig_base_width_per_col = 470;
fig_base_height_per_row = 420;
fig_min_width = 900;
fig_min_height = 600;

% Broken-axis display for comparison scatter.
% This does not delete or hide data points. It transforms display
% coordinates so that the central region is linear and extreme tails are
% compressed into short display regions, similar to plot_size_effect.m.
%
% false: full linear axis, old behavior.
% true : use broken-axis display if extreme values stretch the full range.
use_broken_axis_display = true;

% Percentile of abs(metric values) used to start the broken-axis tail.
% 98 means the central 98%% by absolute value remains linear.
break_start_prctile = 93.0;

% Trigger based on raw_abs_max / break_start.
% 1 always applies broken-axis display when use_broken_axis_display is true
% and raw_abs_max is larger than break_start.
% Larger values only use broken-axis display when extremes are severe.
broken_axis_trigger_ratio = 1;

% Fraction of the central linear half-axis used to display each compressed
% tail. Larger values make the extreme tails occupy more visible space.
tail_display_frac = 0.08;

% Visual gap between the central linear region and each compressed tail.
break_gap_frac = 0.03;

% Minimum display slope in compressed tail.
% 1.0 means tail is not compressed.
% 0.5 means tail distances are shown at half linear scale.
% 0.2 means tail distances are shown at 20% linear scale.
% Increase this if tail points look collapsed into vertical/horizontal lines.
min_tail_display_slope = 0.001;

% Keep x/y limits identical and symmetric around zero. This is recommended
% for comparison scatter plots because y = x, x = 0, and y = 0 are reference
% structures.
force_symmetric_broken_axis = false;

% Add a suffix to output figure names when broken-axis display is actually
% used. This prevents broken-axis figures from overwriting full-range figures.
add_broken_axis_suffix_to_output = true;
broken_axis_file_suffix = '_brokenaxis';

% Draw small slash marks at the broken parts of the x and y axes, matching
% the visual convention used in plot_size_effect.m.
draw_broken_axis_marks = true;
break_mark_line_width = 1.2;

%% ----------------------- Main setup -----------------------

scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir)
    scriptDir = pwd;
end

baseline_fields = normalize_field_list_local(baseline_fields, 'baseline_fields');
comparation_fields = normalize_field_list_local(comparation_fields, 'comparation_fields');
metrics = normalize_field_list_local(metrics, 'metrics');

safe_data_content = sanitize_filename_local(data_content);
contrast_filter = build_contrast_file_filter_local(pick_contrast);

io_dir = resolve_size_effect_io_dir_local(data_content, model_mode, runIdx, scriptDir);

if ~exist(io_dir, 'dir')
    error('Input/output folder does not exist:\n  %s', io_dir);
end

fprintf('Data content: %s\n', data_content);
fprintf('Model mode: %s\n', model_mode);
fprintf('Contrast selection: %s\n', contrast_filter.label);
fprintf('Input/output folder:\n  %s\n', io_dir);

fprintf('\nBaseline fields:\n');
disp(baseline_fields(:));

fprintf('Compared fields:\n');
disp(comparation_fields(:));

fprintf('Metrics:\n');
disp(metrics(:));

%% ----------------------- Load all required size effect results -----------------------

all_fields = unique([baseline_fields, comparation_fields], 'stable');
result_map = struct();

for f = 1:numel(all_fields)
    field_name = all_fields{f};
    key = field_to_key_local(field_name);

    result_file = build_size_effect_mat_file_local( ...
        io_dir, safe_data_content, model_mode, field_name, contrast_filter.file_suffix);

    fprintf('\nLoading size effect result for field %s:\n  %s\n', ...
        field_name, result_file);

    result_map.(key) = load_size_effect_result_local(result_file, field_name, contrast_filter);
end

%% ----------------------- Validate shared metadata across all fields -----------------------

reference_field = all_fields{1};
reference_result = result_map.(field_to_key_local(reference_field));

nUnits = reference_result.nUnits;
groupd = reference_result.groupd(:)';
nGroups = numel(groupd);

group_names = resolve_group_names_local(group_names, reference_result, nGroups);
group_colors = resolve_group_colors_local(probe_colors, nGroups);

for f = 2:numel(all_fields)
    this_field = all_fields{f};
    this_result = result_map.(field_to_key_local(this_field));

    validate_compatible_results_local( ...
        reference_result, this_result, ...
        reference_field, this_field, ...
        data_content, model_mode);
end

group_row_ranges = build_group_row_ranges_local(groupd);

%% ----------------------- Build abbreviated output filename prefix -----------------------

base_fields_tag = join_short_field_names_for_filename_local(baseline_fields);
compared_fields_tag = join_short_field_names_for_filename_local(comparation_fields);
mode_file_tag = model_mode_to_file_tag_local(model_mode);

output_prefix = sprintf('%s_b-%s_c-%s', ...
    safe_data_content, base_fields_tag, compared_fields_tag);

%% ----------------------- Plot one figure per metric -----------------------

nBase = numel(baseline_fields);
nComp = numel(comparation_fields);
nPanels = nBase * nComp;

[nRows, nCols] = choose_panel_layout_local(nPanels, max_panel_cols);

figWidth = max(fig_min_width, fig_base_width_per_col * nCols);
figHeight = max(fig_min_height, fig_base_height_per_row * nRows);

for m = 1:numel(metrics)

    metric_name = metrics{m};
    any_broken_axis_this_metric = false;

    fprintf('\n============================================================\n');
    fprintf('Plotting metric %d/%d: %s\n', m, numel(metrics), metric_name);
    fprintf('============================================================\n');

    hfig = figure( ...
        'Color', 'w', ...
        'Visible', figure_visible, ...
        'Name', sprintf('Size effect comparation: %s', metric_name), ...
        'Position', [100 100 figWidth figHeight]);

    tl = tiledlayout(hfig, nRows, nCols, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    panel_idx = 0;
    legend_handles = gobjects(nGroups, 1);

    for b = 1:nBase
        baseline_field = baseline_fields{b};
        baseline_result = result_map.(field_to_key_local(baseline_field));

        for c = 1:nComp
            comparation_field = comparation_fields{c};
            comparation_result = result_map.(field_to_key_local(comparation_field));

            panel_idx = panel_idx + 1;
            ax = nexttile(tl, panel_idx);
            hold(ax, 'on');

            if ~isfield(baseline_result, metric_name)
                error('Metric %s not found in baseline field result %s.', ...
                    metric_name, baseline_field);
            end

            if ~isfield(comparation_result, metric_name)
                error('Metric %s not found in compared field result %s.', ...
                    metric_name, comparation_field);
            end

            x_all = baseline_result.(metric_name);
            y_all = comparation_result.(metric_name);

            x_all = x_all(:);
            y_all = y_all(:);

            if numel(x_all) ~= nUnits || numel(y_all) ~= nUnits
                error(['Metric vector length mismatch for %s vs %s, metric %s. ', ...
                    'Expected %d units, got %d and %d.'], ...
                    baseline_field, comparation_field, metric_name, ...
                    nUnits, numel(x_all), numel(y_all));
            end

            valid_all = isfinite(x_all) & isfinite(y_all);
            all_x = x_all(valid_all);
            all_y = y_all(valid_all);

axis_info = compute_symmetric_broken_axis_info_local( ...
    all_x, all_y, ...
    use_broken_axis_display, ...
    break_start_prctile, ...
    broken_axis_trigger_ratio, ...
    tail_display_frac, ...
    break_gap_frac, ...
    min_tail_display_slope, ...
    force_symmetric_broken_axis);

            any_broken_axis_this_metric = any_broken_axis_this_metric || axis_info.use_broken_axis;

            % Diagonal reference line y = x. For broken-axis display,
            % draw the linear central segment and compressed tail segments
            % separately, so the skipped raw interval is visibly broken.
            plot_diagonal_reference_line_local( ...
                ax, axis_info, reference_line_style, reference_line_width);

            % Zero reference lines x = 0 and y = 0.
            zero_plot = broken_axis_transform_signed_local(0, axis_info);

            plot(ax, [zero_plot zero_plot], ...
                [axis_info.plot_axis_min axis_info.plot_axis_max], ...
                reference_line_style, ...
                'LineWidth', zero_line_width, ...
                'HandleVisibility', 'off');

            plot(ax, [axis_info.plot_axis_min axis_info.plot_axis_max], ...
                [zero_plot zero_plot], ...
                reference_line_style, ...
                'LineWidth', zero_line_width, ...
                'HandleVisibility', 'off');

            for g = 1:nGroups
                rows = group_row_ranges{g};

                x = x_all(rows);
                y = y_all(rows);

                valid = isfinite(x) & isfinite(y);
                x = x(valid);
                y = y(valid);

                if isempty(x)
                    continue;
                end

                x_plot = broken_axis_transform_signed_local(x, axis_info);
                y_plot = broken_axis_transform_signed_local(y, axis_info);

                thisColor = group_colors(g, :);

                if use_marker_alpha
                    h = scatter(ax, x_plot, y_plot, marker_size, ...
                        'filled', ...
                        'MarkerFaceColor', thisColor, ...
                        'MarkerEdgeColor', thisColor, ...
                        'MarkerFaceAlpha', marker_alpha, ...
                        'MarkerEdgeAlpha', marker_alpha, ...
                        'DisplayName', group_names{g});
                else
                    h = scatter(ax, x_plot, y_plot, marker_size, ...
                        'filled', ...
                        'MarkerFaceColor', thisColor, ...
                        'MarkerEdgeColor', thisColor, ...
                        'DisplayName', group_names{g});
                end

                if panel_idx == 1
                    legend_handles(g) = h;
                end
            end

            axis(ax, 'square');
            xlim(ax, [axis_info.plot_axis_min axis_info.plot_axis_max]);
            ylim(ax, [axis_info.plot_axis_min axis_info.plot_axis_max]);
            xticks(ax, axis_info.plot_ticks);
            yticks(ax, axis_info.plot_ticks);
            xticklabels(ax, axis_info.tick_labels);
            yticklabels(ax, axis_info.tick_labels);

            xlabel(ax, sprintf('%s %s', baseline_field, metric_label_local(metric_name)), ...
                'Interpreter', 'none');

            ylabel(ax, sprintf('%s %s', comparation_field, metric_label_local(metric_name)), ...
                'Interpreter', 'none');

            panel_title = sprintf('base: %s\ncompared: %s', ...
                baseline_field, comparation_field);

            title(ax, panel_title, 'Interpreter', 'none');

            clean_axis_local(ax);

            if axis_info.use_broken_axis && draw_broken_axis_marks
                draw_axis_break_marks_signed_local(ax, axis_info, break_mark_line_width);
            end
        end
    end

    sgtitle(tl, sprintf('%s | %s | %s | %s | neuron-wise size effect comparation', ...
        data_content, model_mode, contrast_filter.label, metric_name), ...
        'Interpreter', 'none');

    valid_legend_handles = legend_handles(isgraphics(legend_handles));
    if ~isempty(valid_legend_handles)
        legend_names = group_names(isgraphics(legend_handles));
        lgd = legend(valid_legend_handles, legend_names, ...
            'Interpreter', 'none', ...
            'Location', 'eastoutside', ...
            'Box', 'off');
        lgd.Layout.Tile = 'east';
    end

    metric_file_tag = metric_to_file_tag_local(metric_name);

    output_suffix = contrast_filter.file_suffix;
    if add_broken_axis_suffix_to_output && any_broken_axis_this_metric
        output_suffix = [output_suffix, broken_axis_file_suffix];
    end

    output_base_name = sprintf('%s_%s_%s%s', ...
        output_prefix, metric_file_tag, mode_file_tag, output_suffix);

    if save_fig
        save_current_figure_local(hfig, io_dir, output_base_name, ...
            save_png, save_matlab_fig, png_dpi);
    end

    if close_after_save
        close(hfig);
    end
end

fprintf('\nDone.\n');

%% =========================================================================
% Local functions
% =========================================================================

function fields = normalize_field_list_local(fields, var_name)
    if ischar(fields)
        fields = {fields};

    elseif isstring(fields)
        fields = cellstr(fields(:))';

    elseif iscell(fields)
        fields = reshape(fields, 1, []);

        for i = 1:numel(fields)
            if isstring(fields{i})
                fields{i} = char(fields{i});
            end

            if ~ischar(fields{i})
                error('%s{%d} must be a char or string.', var_name, i);
            end
        end

    else
        error('%s must be a char, string, string array, or cell array.', var_name);
    end

    if isempty(fields)
        error('%s is empty.', var_name);
    end

    empty_mask = cellfun(@isempty, fields);
    if any(empty_mask)
        error('%s contains empty entries.', var_name);
    end

    if numel(unique(fields, 'stable')) ~= numel(fields)
        warning('%s contains duplicate entries. Duplicates will be removed.', var_name);
        fields = unique(fields, 'stable');
        fields = reshape(fields, 1, []);
    end
end

function io_dir = resolve_size_effect_io_dir_local(data_content, model_mode, runIdx, scriptDir)
    switch model_mode
        case 'all_condition_model'
            baseDir = ['./FA_Dlag_', data_content];
            io_dir = fullfile(baseDir, 'mat_results', sprintf('run%03d', runIdx));

        case 'condition_specific_models'
            io_dir = scriptDir;

        otherwise
            error(['Unknown model_mode: %s. Expected all_condition_model ', ...
                'or condition_specific_models.'], model_mode);
    end
end

function result_file = build_size_effect_mat_file_local( ...
    io_dir, safe_data_content, model_mode, field_name, contrast_file_suffix)

    safe_field = sanitize_filename_local(field_name);

    result_file = fullfile(io_dir, sprintf('%s_%s_size_effect_%s%s.mat', ...
        safe_data_content, model_mode, safe_field, contrast_file_suffix));

    if ~isfile(result_file)
        error('Size effect result file not found:\n  %s', result_file);
    end
end

function result = load_size_effect_result_local(result_file, expected_field, contrast_filter)
    S = load(result_file);

    if ~isfield(S, 'size_effect_result')
        error('File does not contain size_effect_result:\n  %s', result_file);
    end

    result = S.size_effect_result;

    required_fields = { ...
        'data_content', ...
        'model_mode', ...
        'analysis_field', ...
        'nUnits', ...
        'groupd', ...
        'classic_SI', ...
        'delta_SL', ...
        'S_norm_diff'};

    for i = 1:numel(required_fields)
        if ~isfield(result, required_fields{i})
            error('size_effect_result in %s is missing field %s.', ...
                result_file, required_fields{i});
        end
    end

    if ~strcmp(result.analysis_field, expected_field)
        warning(['Loaded result file analysis_field is %s, but expected %s. ', ...
            'Continuing because file name matched expected field.'], ...
            result.analysis_field, expected_field);
    end

    validate_contrast_metadata_local(result, contrast_filter, result_file, expected_field);
end


function contrast_filter = build_contrast_file_filter_local(pick_contrast)
% Build file suffix and label matching plot_size_effect.m.
%
% This comparison script is downstream only. It does not decide which
% conditions/trials are low or high contrast. That filtering must already
% have been done by plot_size_effect.m. Here we only select the matching
% result files by suffix and check metadata when available.

    if isempty(pick_contrast)
        pick_contrast = 0;
    end

    if ~(isnumeric(pick_contrast) || islogical(pick_contrast)) || ~isscalar(pick_contrast)
        error('pick_contrast must be a scalar value: 0, 1, or 2.');
    end

    pick_contrast = double(pick_contrast);

    contrast_filter = struct();
    contrast_filter.pick_contrast = pick_contrast;

    switch pick_contrast
        case 0
            contrast_filter.label = 'all_contrasts';
            contrast_filter.file_suffix = '';

        case 1
            contrast_filter.label = 'low_contrast';
            contrast_filter.file_suffix = '_low_contrast';

        case 2
            contrast_filter.label = 'high_contrast';
            contrast_filter.file_suffix = '_high_contrast';

        otherwise
            error('pick_contrast must be 0, 1, or 2.');
    end
end

function validate_contrast_metadata_local(result, contrast_filter, result_file, expected_field)
% Validate that loaded result matches the requested contrast selection.
%
% For pick_contrast = 0, old result files may not contain contrast metadata,
% so missing metadata is allowed. If metadata exists, it is checked.
% For pick_contrast = 1 or 2, contrast metadata must exist and match.

    expected_pick = contrast_filter.pick_contrast;

    if expected_pick == 0
        if isfield(result, 'pick_contrast') && ~isempty(result.pick_contrast)
            if double(result.pick_contrast) ~= 0
                warning(['Loaded field %s has pick_contrast = %g, but this ', ...
                    'script requested pick_contrast = 0. File:\n  %s'], ...
                    expected_field, double(result.pick_contrast), result_file);
            end
        end

        if isfield(result, 'contrast_file_suffix') && ~isempty(result.contrast_file_suffix)
            if ~strcmp(char(result.contrast_file_suffix), contrast_filter.file_suffix)
                warning(['Loaded field %s has contrast_file_suffix = %s, ', ...
                    'but this script requested no suffix. File:\n  %s'], ...
                    expected_field, char(result.contrast_file_suffix), result_file);
            end
        end

        return;
    end

    required_fields = {'pick_contrast', 'contrast_label', 'contrast_file_suffix'};

    for i = 1:numel(required_fields)
        fn = required_fields{i};
        if ~isfield(result, fn)
            error(['For pick_contrast = %d, size_effect_result for field %s ', ...
                'must contain metadata field %s. This usually means the file ', ...
                'was not generated by the updated plot_size_effect.m. File:\n  %s'], ...
                expected_pick, expected_field, fn, result_file);
        end
    end

    if double(result.pick_contrast) ~= expected_pick
        error(['Contrast mismatch for field %s. File has pick_contrast = %g, ', ...
            'but this script requested %g. File:\n  %s'], ...
            expected_field, double(result.pick_contrast), expected_pick, result_file);
    end

    if ~strcmp(char(result.contrast_label), contrast_filter.label)
        error(['Contrast label mismatch for field %s. File has %s, expected %s. ', ...
            'File:\n  %s'], ...
            expected_field, char(result.contrast_label), contrast_filter.label, result_file);
    end

    if ~strcmp(char(result.contrast_file_suffix), contrast_filter.file_suffix)
        error(['Contrast suffix mismatch for field %s. File has %s, expected %s. ', ...
            'File:\n  %s'], ...
            expected_field, char(result.contrast_file_suffix), contrast_filter.file_suffix, result_file);
    end
end

function validate_compatible_results_local( ...
    reference_result, this_result, reference_field, this_field, ...
    expected_data_content, expected_model_mode)

    if ~strcmp(this_result.data_content, expected_data_content)
        error('Field %s data_content is %s, expected %s.', ...
            this_field, this_result.data_content, expected_data_content);
    end

    if ~strcmp(this_result.model_mode, expected_model_mode)
        error('Field %s model_mode is %s, expected %s.', ...
            this_field, this_result.model_mode, expected_model_mode);
    end

    if ~strcmp(reference_result.data_content, this_result.data_content)
        error('data_content mismatch between %s and %s.', ...
            reference_field, this_field);
    end

    if ~strcmp(reference_result.model_mode, this_result.model_mode)
        error('model_mode mismatch between %s and %s.', ...
            reference_field, this_field);
    end

    if reference_result.nUnits ~= this_result.nUnits
        error('nUnits mismatch between %s and %s: %d vs %d.', ...
            reference_field, this_field, reference_result.nUnits, this_result.nUnits);
    end

    if ~isequal(reference_result.groupd(:)', this_result.groupd(:)')
        error('groupd mismatch between %s and %s.', ...
            reference_field, this_field);
    end

    optional_compare_fields = { ...
        'runIdx', ...
        'stim_tag', ...
        'small_size', ...
        'large_size', ...
        'n_small_trials', ...
        'n_large_trials', ...
        'pick_contrast', ...
        'contrast_label', ...
        'contrast_file_suffix'};

    for i = 1:numel(optional_compare_fields)
        fn = optional_compare_fields{i};

        if isfield(reference_result, fn) && isfield(this_result, fn)
            ref_val = reference_result.(fn);
            this_val = this_result.(fn);

            if ischar(ref_val) || isstring(ref_val)
                if ~strcmp(char(ref_val), char(this_val))
                    warning('%s differs between %s and %s.', ...
                        fn, reference_field, this_field);
                end
            elseif isnumeric(ref_val) || islogical(ref_val)
                if ~isequal(ref_val, this_val)
                    warning('%s differs between %s and %s.', ...
                        fn, reference_field, this_field);
                end
            end
        end
    end
end

function group_names = resolve_group_names_local(group_names, result, nGroups)
    if isempty(group_names)
        if isfield(result, 'group_names') && ~isempty(result.group_names)
            group_names = result.group_names;
        else
            group_names = cell(1, nGroups);
            for g = 1:nGroups
                group_names{g} = sprintf('Group %d neurons', g);
            end
        end
    end

    if isstring(group_names)
        group_names = cellstr(group_names);
    end

    group_names = reshape(group_names, 1, []);

    if ~iscell(group_names) || numel(group_names) ~= nGroups
        error('group_names must be empty or contain exactly %d entries.', nGroups);
    end

    for g = 1:nGroups
        if isstring(group_names{g})
            group_names{g} = char(group_names{g});
        end

        if ~ischar(group_names{g})
            error('group_names{%d} must be a char or string.', g);
        end
    end
end

function group_colors = resolve_group_colors_local(probe_colors, nGroups)
    if size(probe_colors, 1) < nGroups
        warning(['probe_colors has fewer rows than number of groups. ', ...
            'Extra groups will be plotted in black.']);
    end

    group_colors = zeros(nGroups, 3);

    for g = 1:nGroups
        if g <= size(probe_colors, 1)
            group_colors(g, :) = probe_colors(g, :);
        else
            group_colors(g, :) = [0, 0, 0];
        end
    end
end

function group_row_ranges = build_group_row_ranges_local(groupd)
    groupd = groupd(:)';
    nGroups = numel(groupd);
    group_row_ranges = cell(1, nGroups);

    row_start = 1;
    for g = 1:nGroups
        row_end = row_start + groupd(g) - 1;
        group_row_ranges{g} = row_start:row_end;
        row_start = row_end + 1;
    end
end

function axis_info = compute_symmetric_broken_axis_info_local( ...
    x, y, use_broken_axis_display, break_start_prctile, ...
    broken_axis_trigger_ratio, tail_display_frac, break_gap_frac, ...
    min_tail_display_slope, force_symmetric_broken_axis)
% Compute display transform information for a signed symmetric broken axis.
%
% This does not remove points. It maps raw metric values to plotting
% coordinates. Values within [-break_start, break_start] are shown linearly.
% Extreme positive and negative tails are compressed into short display
% regions.

    if nargin < 3 || isempty(use_broken_axis_display)
        use_broken_axis_display = false;
    end

    if nargin < 4 || isempty(break_start_prctile)
        break_start_prctile = 98.0;
    end

    if nargin < 5 || isempty(broken_axis_trigger_ratio)
        broken_axis_trigger_ratio = 1;
    end

    if nargin < 6 || isempty(tail_display_frac)
        tail_display_frac = 0.08;
    end

    if nargin < 7 || isempty(break_gap_frac)
        break_gap_frac = 0.03;
    end

if nargin < 8 || isempty(min_tail_display_slope)
    min_tail_display_slope = 0.25;
end

if nargin < 9 || isempty(force_symmetric_broken_axis)
    force_symmetric_broken_axis = true;
end

if ~(isscalar(min_tail_display_slope) && isfinite(min_tail_display_slope) ...
        && min_tail_display_slope > 0 && min_tail_display_slope <= 1)
    error('min_tail_display_slope must be a finite scalar in (0, 1].');
end

    if ~(isscalar(break_start_prctile) && isfinite(break_start_prctile) ...
            && break_start_prctile > 0 && break_start_prctile < 100)
        error('break_start_prctile must be a scalar between 0 and 100.');
    end

    if ~(isscalar(broken_axis_trigger_ratio) && isfinite(broken_axis_trigger_ratio) ...
            && broken_axis_trigger_ratio >= 1)
        error('broken_axis_trigger_ratio must be a finite scalar >= 1.');
    end

    vals = [x(:); y(:)];
    vals = vals(isfinite(vals));

    axis_info = struct();
    axis_info.use_broken_axis = false;
    axis_info.break_start_prctile = break_start_prctile;
    axis_info.broken_axis_trigger_ratio = broken_axis_trigger_ratio;
    axis_info.tail_display_frac = tail_display_frac;
    axis_info.break_gap_frac = break_gap_frac;
    axis_info.min_tail_display_slope = min_tail_display_slope;
    axis_info.raw_axis_min = NaN;
    axis_info.raw_axis_max = NaN;
    axis_info.raw_abs_max = NaN;
    axis_info.break_start = NaN;
    axis_info.break_end = NaN;
    axis_info.tail_display_len = NaN;
    axis_info.break_gap = NaN;
    axis_info.plot_axis_min = NaN;
    axis_info.plot_axis_max = NaN;
    axis_info.plot_ticks = [];
    axis_info.tick_labels = {};

    if isempty(vals)
        axis_info.raw_axis_min = -1;
        axis_info.raw_axis_max = 1;
        axis_info.raw_abs_max = 1;
        axis_info.break_start = 1;
        axis_info.break_end = 1;
        axis_info.tail_display_len = 0;
        axis_info.break_gap = 0;
        axis_info.plot_axis_min = -1;
        axis_info.plot_axis_max = 1;
        [axis_info.plot_ticks, axis_info.tick_labels] = build_broken_axis_ticks_local(axis_info);
        return;
    end

    raw_min = min(vals);
    raw_max = max(vals);
    raw_abs_max = max(abs([raw_min, raw_max]));

    if raw_abs_max <= 0 || ~isfinite(raw_abs_max)
        raw_abs_max = 1;
    end

    if force_symmetric_broken_axis
        raw_axis_min = -raw_abs_max;
        raw_axis_max = raw_abs_max;
    else
        raw_axis_min = raw_min;
        raw_axis_max = raw_max;
    end

    abs_vals = abs(vals);
    abs_vals = abs_vals(isfinite(abs_vals));
    break_start = percentile_local(abs_vals, break_start_prctile);

    if isempty(break_start) || ~isfinite(break_start) || break_start <= 0
        break_start = raw_abs_max;
    end

    use_broken_axis = use_broken_axis_display ...
        && raw_abs_max > break_start * broken_axis_trigger_ratio;

    axis_info.raw_axis_min = raw_axis_min;
    axis_info.raw_axis_max = raw_axis_max;
    axis_info.raw_abs_max = raw_abs_max;

    if ~use_broken_axis
        axis_info.break_start = raw_abs_max;
        axis_info.break_end = raw_abs_max;
        axis_info.tail_display_len = 0;
        axis_info.break_gap = 0;
        axis_info.plot_axis_min = raw_axis_min;
        axis_info.plot_axis_max = raw_axis_max;

        pad = 0.06 * max(eps, axis_info.plot_axis_max - axis_info.plot_axis_min);
        axis_info.plot_axis_min = axis_info.plot_axis_min - pad;
        axis_info.plot_axis_max = axis_info.plot_axis_max + pad;

        [axis_info.plot_ticks, axis_info.tick_labels] = build_broken_axis_ticks_local(axis_info);
        return;
    end

    high_abs_vals = abs_vals(abs_vals > break_start);
    break_end = min(high_abs_vals);

    if isempty(break_end) || ~isfinite(break_end) || break_end <= break_start
        break_end = break_start;
    end

raw_tail_span = max(eps, raw_abs_max - break_end);

tail_display_len_from_frac = max(eps, break_start * tail_display_frac);
tail_display_len_from_slope = raw_tail_span * min_tail_display_slope;

tail_display_len = max(tail_display_len_from_frac, tail_display_len_from_slope);
break_gap = max(eps, break_start * break_gap_frac);

    axis_info.use_broken_axis = true;
    axis_info.break_start = break_start;
    axis_info.break_end = break_end;
    axis_info.tail_display_len = tail_display_len;
    axis_info.break_gap = break_gap;

    plot_min = broken_axis_transform_signed_local(raw_axis_min, axis_info);
    plot_max = broken_axis_transform_signed_local(raw_axis_max, axis_info);

    if force_symmetric_broken_axis
        plot_abs_max = max(abs([plot_min, plot_max]));
        plot_min = -plot_abs_max;
        plot_max = plot_abs_max;
    end

    pad = 0.06 * max(eps, plot_max - plot_min);
    axis_info.plot_axis_min = plot_min - pad;
    axis_info.plot_axis_max = plot_max + pad;

    [axis_info.plot_ticks, axis_info.tick_labels] = build_broken_axis_ticks_local(axis_info);
end

function x_plot = broken_axis_transform_signed_local(x_raw, axis_info)
% Signed broken-axis transform.
%
% For |x| <= break_start:
%   x_plot = x_raw
%
% For break_start < |x| < break_end:
%   this skipped raw interval is mapped into the visual break gap.
%
% For |x| >= break_end:
%   the interval [break_end, raw_abs_max] is linearly compressed into
%   [break_start + break_gap, break_start + break_gap + tail_display_len].

    x_plot = x_raw;

    if ~axis_info.use_broken_axis
        return;
    end

    sgn = sign(x_raw);
    ax = abs(x_raw);

    break_start = axis_info.break_start;
    break_end = axis_info.break_end;
    raw_abs_max = axis_info.raw_abs_max;
    tail_display_len = axis_info.tail_display_len;
    break_gap = axis_info.break_gap;

    x_plot_abs = ax;

    gap_mask = ax > break_start & ax < break_end;
    tail_mask = ax >= break_end;

    if break_end > break_start
        x_plot_abs(gap_mask) = break_start ...
            + (ax(gap_mask) - break_start) ./ (break_end - break_start) .* break_gap;
    else
        x_plot_abs(gap_mask) = break_start + break_gap;
    end

    if raw_abs_max > break_end
        x_plot_abs(tail_mask) = break_start + break_gap ...
            + (ax(tail_mask) - break_end) ./ (raw_abs_max - break_end) .* tail_display_len;
    else
        x_plot_abs(tail_mask) = break_start + break_gap + tail_display_len;
    end

    x_plot = sgn .* x_plot_abs;
end

function [plot_ticks, tick_labels] = build_broken_axis_ticks_local(axis_info)
% Build ticks in plot coordinates with labels in raw coordinates.
%
% In broken-axis mode, tick labels are kept in the pre-break linear region
% only. The compressed tail still contains all points, but its extreme raw
% values are not labeled, matching plot_size_effect.m.

    if axis_info.use_broken_axis
        raw_ticks = choose_prebreak_ticks_signed_local(axis_info.break_start);
        raw_ticks = unique_with_tolerance_local(raw_ticks, 1e-10);
        plot_ticks = broken_axis_transform_signed_local(raw_ticks, axis_info);
        tick_labels = compose_numeric_tick_labels_local(raw_ticks);
    else
        raw_ticks = choose_linear_ticks_symmetric_local( ...
            axis_info.raw_axis_min, axis_info.raw_axis_max);
        plot_ticks = raw_ticks;
        tick_labels = compose_numeric_tick_labels_local(raw_ticks);
    end
end

function raw_ticks = choose_prebreak_ticks_signed_local(prebreak_abs_max)
% Choose simple signed ticks for the linear part of a broken axis.

    if isempty(prebreak_abs_max) || ~isfinite(prebreak_abs_max) || prebreak_abs_max <= 0
        raw_ticks = 0;
        return;
    end

    target_intervals = 4;
    rough_step = (2 * prebreak_abs_max) / target_intervals;
    step = choose_nice_numeric_step_local(rough_step);

    if step <= 0 || ~isfinite(step)
        raw_ticks = linspace(-prebreak_abs_max, prebreak_abs_max, 5);
        raw_ticks(abs(raw_ticks) < 1e-12) = 0;
        return;
    end

    max_tick = floor(prebreak_abs_max / step) * step;

    if max_tick <= 0
        raw_ticks = [-prebreak_abs_max, 0, prebreak_abs_max];
    else
        raw_ticks = -max_tick:step:max_tick;
        if ~any(abs(raw_ticks) < 1e-12)
            raw_ticks = sort([raw_ticks, 0]);
        end
    end

    raw_ticks(abs(raw_ticks) < 1e-12) = 0;
end

function step = choose_nice_numeric_step_local(rough_step)
% Choose a nice numeric tick step.

    if rough_step <= 0 || ~isfinite(rough_step)
        step = 1;
        return;
    end

    exponent = floor(log10(rough_step));
    base = 10 ^ exponent;

    candidates = [1 2 2.5 5 10] * base;
    candidates = candidates(candidates >= rough_step);

    if isempty(candidates)
        step = 10 * base;
    else
        step = candidates(1);
    end
end

function ticks = choose_linear_ticks_symmetric_local(axis_min, axis_max)
% Choose simple ticks for a linear signed axis.

    lim = max(abs([axis_min, axis_max]));
    if lim <= 0 || ~isfinite(lim)
        lim = 1;
    end

    ticks = linspace(-lim, lim, 5);
end

function vals_unique = unique_with_tolerance_local(vals, tol)
% Unique values preserving order with tolerance.

    vals = vals(:)';
    vals_unique = [];

    for i = 1:numel(vals)
        if isempty(vals_unique) || all(abs(vals(i) - vals_unique) > tol)
            vals_unique(end+1) = vals(i); %#ok<AGROW>
        end
    end
end

function labels = compose_numeric_tick_labels_local(vals)
% Compact numeric tick labels.

    labels = cell(size(vals));

    for i = 1:numel(vals)
        v = vals(i);

        if abs(v) < 1e-12
            v = 0;
        end

        if abs(v) >= 1000 || (abs(v) > 0 && abs(v) < 0.001)
            labels{i} = sprintf('%.2g', v);
        elseif abs(v - round(v)) < 1e-10
            labels{i} = sprintf('%d', round(v));
        else
            labels{i} = sprintf('%.3g', v);
        end
    end
end

function plot_diagonal_reference_line_local(ax, axis_info, line_style, line_width)
% Plot y = x in display coordinates.
%
% In broken-axis mode, draw separate central and tail segments so the
% diagonal line does not visually bridge the broken raw interval.

    if ~axis_info.use_broken_axis
        raw_ref = linspace(axis_info.raw_axis_min, axis_info.raw_axis_max, 300);
        plot_ref = broken_axis_transform_signed_local(raw_ref, axis_info);

        plot(ax, plot_ref, plot_ref, ...
            line_style, ...
            'LineWidth', line_width, ...
            'HandleVisibility', 'off');
        return;
    end

    % Central linear part.
    lo = max(axis_info.raw_axis_min, -axis_info.break_start);
    hi = min(axis_info.raw_axis_max, axis_info.break_start);

    if hi > lo
        raw_ref = linspace(lo, hi, 150);
        plot_ref = broken_axis_transform_signed_local(raw_ref, axis_info);
        plot(ax, plot_ref, plot_ref, ...
            line_style, ...
            'LineWidth', line_width, ...
            'HandleVisibility', 'off');
    end

    % Positive compressed tail.
    if axis_info.raw_axis_max >= axis_info.break_end
        lo = max(axis_info.break_end, axis_info.raw_axis_min);
        hi = axis_info.raw_axis_max;

        if hi > lo
            raw_ref = linspace(lo, hi, 100);
            plot_ref = broken_axis_transform_signed_local(raw_ref, axis_info);
            plot(ax, plot_ref, plot_ref, ...
                line_style, ...
                'LineWidth', line_width, ...
                'HandleVisibility', 'off');
        end
    end

    % Negative compressed tail.
    if axis_info.raw_axis_min <= -axis_info.break_end
        lo = axis_info.raw_axis_min;
        hi = min(-axis_info.break_end, axis_info.raw_axis_max);

        if hi > lo
            raw_ref = linspace(lo, hi, 100);
            plot_ref = broken_axis_transform_signed_local(raw_ref, axis_info);
            plot(ax, plot_ref, plot_ref, ...
                line_style, ...
                'LineWidth', line_width, ...
                'HandleVisibility', 'off');
        end
    end
end

function draw_axis_break_marks_signed_local(ax, axis_info, line_width)
% Draw slash marks on the broken parts of the x and y axes.
%
% This follows the same visual idea as plot_size_effect.m, extended to a
% signed symmetric axis. Marks are placed at positive and/or negative breaks
% when those raw ranges are displayed.

    if ~axis_info.use_broken_axis
        return;
    end

    if nargin < 3 || isempty(line_width)
        line_width = 1.2;
    end

    axes(ax); %#ok<LAXES>
    hold(ax, 'on');

    xLim = ax.XLim;
    yLim = ax.YLim;

    display_span = max(eps, max([diff(xLim), diff(yLim)]));
    slash_dx = display_span * 0.012;
    slash_dy = display_span * 0.025;
    offset = display_span * 0.018;

    x0 = xLim(1);
    y0 = yLim(1);

    break_center_abs = axis_info.break_start + axis_info.break_gap / 2;

    x_centers = [];
    if axis_info.raw_axis_max > axis_info.break_start
        x_centers(end+1) = break_center_abs; %#ok<AGROW>
    end
    if axis_info.raw_axis_min < -axis_info.break_start
        x_centers(end+1) = -break_center_abs; %#ok<AGROW>
    end

    for i = 1:numel(x_centers)
        xc = x_centers(i);

        plot(ax, ...
            [xc - slash_dx, xc + slash_dx], ...
            [y0 + slash_dy, y0 - slash_dy], ...
            'k-', 'LineWidth', line_width, 'Clipping', 'off', ...
            'HandleVisibility', 'off');

        plot(ax, ...
            [xc - slash_dx + offset, xc + slash_dx + offset], ...
            [y0 + slash_dy, y0 - slash_dy], ...
            'k-', 'LineWidth', line_width, 'Clipping', 'off', ...
            'HandleVisibility', 'off');
    end

    y_centers = [];
    if axis_info.raw_axis_max > axis_info.break_start
        y_centers(end+1) = break_center_abs; %#ok<AGROW>
    end
    if axis_info.raw_axis_min < -axis_info.break_start
        y_centers(end+1) = -break_center_abs; %#ok<AGROW>
    end

    for i = 1:numel(y_centers)
        yc = y_centers(i);

        plot(ax, ...
            [x0 + slash_dx, x0 - slash_dx], ...
            [yc - slash_dy, yc + slash_dy], ...
            'k-', 'LineWidth', line_width, 'Clipping', 'off', ...
            'HandleVisibility', 'off');

        plot(ax, ...
            [x0 + slash_dx, x0 - slash_dx], ...
            [yc - slash_dy + offset, yc + slash_dy + offset], ...
            'k-', 'LineWidth', line_width, 'Clipping', 'off', ...
            'HandleVisibility', 'off');
    end
end

function q = percentile_local(x, p)
% Small local percentile helper to avoid Statistics Toolbox dependency.

    x = x(:);
    x = x(isfinite(x));

    if isempty(x)
        q = NaN;
        return;
    end

    x = sort(x);
    n = numel(x);

    if n == 1
        q = x;
        return;
    end

    p = max(0, min(100, p));
    pos = 1 + (n - 1) * p / 100;
    lo = floor(pos);
    hi = ceil(pos);

    if lo == hi
        q = x(lo);
    else
        w = pos - lo;
        q = (1 - w) * x(lo) + w * x(hi);
    end
end

function label = metric_label_local(metric_name)
    switch metric_name
        case 'classic_SI'
            label = 'classic SI';

        case 'delta_SL'
            label = 'delta S-L';

        case 'S_norm_diff'
            label = 'S norm diff';

        otherwise
            label = metric_name;
    end
end

function key = field_to_key_local(field_name)
    key = sanitize_filename_local(field_name);

    if isempty(regexp(key(1), '[A-Za-z]', 'once'))
        key = ['field_', key];
    end

    key = matlab.lang.makeValidName(key);
end

function clean_axis_local(ax)
    grid(ax, 'off');
    box(ax, 'off');
    set(ax, ...
        'TickDir', 'out', ...
        'LineWidth', 1, ...
        'FontSize', 11);
end

function save_current_figure_local(hfig, fig_out_dir, base_name, save_png, save_matlab_fig, png_dpi)
    if ~exist(fig_out_dir, 'dir')
        mkdir(fig_out_dir);
    end

    if save_png
        png_file = fullfile(fig_out_dir, sprintf('%s.png', base_name));
        save_png_local(hfig, png_file, png_dpi);
        fprintf('\nSaved PNG figure:\n  %s\n', png_file);
    end

    if save_matlab_fig
        fig_file = fullfile(fig_out_dir, sprintf('%s.fig', base_name));
        savefig(hfig, fig_file);
        fprintf('Saved MATLAB figure:\n  %s\n', fig_file);
    end
end

function save_png_local(fig, pngFile, dpi)
    drawnow;

    try
        if exist('exportgraphics', 'file') == 2
            exportgraphics(fig, pngFile, ...
                'Resolution', dpi, ...
                'BackgroundColor', 'white');
        else
            set(fig, 'PaperPositionMode', 'auto');
            print(fig, pngFile, '-dpng', sprintf('-r%d', dpi));
        end
    catch
        warning('exportgraphics/print failed. Falling back to saveas.');
        saveas(fig, pngFile);
    end
end

function name = sanitize_filename_local(name)
    if isstring(name)
        name = char(name);
    end

    name = regexprep(name, '[^a-zA-Z0-9_\-]', '_');
    name = regexprep(name, '_+', '_');
    name = strtrim(name);

    if isempty(name)
        name = 'unnamed';
    end
end


function [nRows, nCols] = choose_panel_layout_local(nPanels, max_panel_cols)
    if nPanels < 1
        error('nPanels must be >= 1.');
    end

    if nargin < 2 || isempty(max_panel_cols)
        max_panel_cols = 4;
    end

    max_panel_cols = max(1, max_panel_cols);
    max_panel_cols = min(max_panel_cols, nPanels);

    best_score = inf;
    best_rows = 1;
    best_cols = 1;

    for c = 1:max_panel_cols
        r = ceil(nPanels / c);
        empty_panels = r * c - nPanels;

        % Prefer layouts close to square, but slightly wider than tall.
        aspect_penalty = abs(c / r - 1.35);

        % Strongly penalize empty panels.
        empty_penalty = empty_panels * 10;

        % Mildly penalize too many rows.
        row_penalty = r * 0.1;

        score = empty_penalty + aspect_penalty + row_penalty;

        if score < best_score
            best_score = score;
            best_rows = r;
            best_cols = c;
        end
    end

    nRows = best_rows;
    nCols = best_cols;
end

function mode_tag = model_mode_to_file_tag_local(model_mode)
    switch model_mode
        case 'all_condition_model'
            mode_tag = 'all';

        case 'condition_specific_models'
            mode_tag = 'csm';

        otherwise
            mode_tag = sanitize_filename_local(model_mode);
            mode_tag = compress_generic_name_local(mode_tag);
    end
end

function metric_tag = metric_to_file_tag_local(metric_name)
    switch metric_name
        case 'classic_SI'
            metric_tag = 'SI';

        case 'delta_SL'
            metric_tag = 'dSL';

        case 'S_norm_diff'
            metric_tag = 'SnD';

        otherwise
            metric_tag = sanitize_filename_local(metric_name);
            metric_tag = compress_generic_name_local(metric_tag);
    end
end

function joined_name = join_short_field_names_for_filename_local(fields)
    short_fields = cell(size(fields));

    for i = 1:numel(fields)
        short_fields{i} = analysis_field_to_file_tag_local(fields{i});
    end

    joined_name = strjoin(short_fields, '-');
end

function field_tag = analysis_field_to_file_tag_local(field_name)
    switch field_name
        case 'y'
            field_tag = 'y';

        case 'd'
            field_tag = 'd';

        case 'yRecon_use_all'
            field_tag = 'yall';

        case 'yRecon_use_all_no_d'
            field_tag = 'yallND';

        case 'yRecon_use_across'
            field_tag = 'yacr';

        case 'yRecon_use_across_no_d'
            field_tag = 'yacrND';

        case 'yRecon_use_within'
            field_tag = 'ywin';

        case 'yRecon_use_within_no_d'
            field_tag = 'ywinND';

        case 'yRecon_across_excl_within'
            field_tag = 'yacrXwin';

        case 'yRecon_within_excl_across'
            field_tag = 'ywinXacr';

        case 'yRecon_use_all_with_R'
            field_tag = 'yallR';

        case 'yRecon_use_across_with_R'
            field_tag = 'yacrR';

        case 'yRecon_use_within_with_R'
            field_tag = 'ywinR';

        case 'yRecon_across_excl_within_with_R'
            field_tag = 'yacrXwinR';

        case 'yRecon_within_excl_across_with_R'
            field_tag = 'ywinXacrR';

        case 'yRecon_use_all_keep_resid'
            field_tag = 'yallKR';

        case 'yRecon_use_across_keep_resid'
            field_tag = 'yacrKR';

        case 'yRecon_use_within_keep_resid'
            field_tag = 'ywinKR';

        case 'yRecon_across_excl_within_keep_resid'
            field_tag = 'yacrXwinKR';

        case 'yRecon_within_excl_across_keep_resid'
            field_tag = 'ywinXacrKR';

        otherwise
            field_tag = sanitize_filename_local(field_name);
            field_tag = strrep(field_tag, 'yRecon_', 'y');
            field_tag = strrep(field_tag, 'use_', '');
            field_tag = strrep(field_tag, 'across', 'acr');
            field_tag = strrep(field_tag, 'within', 'win');
            field_tag = strrep(field_tag, 'excl', 'X');
            field_tag = strrep(field_tag, 'condition', 'cond');
            field_tag = strrep(field_tag, 'resid', 'res');
            field_tag = compress_generic_name_local(field_tag);
    end
end

function short_name = compress_generic_name_local(name)
    short_name = name;

    replacements = { ...
        'demean', 'dm'; ...
        'count', 'cnt'; ...
        'within', 'win'; ...
        'trial', 'tr'; ...
        'condition', 'cond'; ...
        'conditions', 'conds'; ...
        'across', 'acr'; ...
        'pooled', 'pool'; ...
        'reconstruction', 'recon'; ...
        'specific', 'spec'; ...
        'model', 'mdl'; ...
        'models', 'mdls'};

    for i = 1:size(replacements, 1)
        short_name = strrep(short_name, replacements{i, 1}, replacements{i, 2});
    end

    short_name = regexprep(short_name, '_+', '_');
    short_name = regexprep(short_name, '^_|_$', '');
end